version: "3.9"
services:

  postgres:
    image: docker.io/postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  nginx:
    image: docker.io/nginx:1.17.9
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/general.conf:/etc/nginx/general.conf:ro
      - ./nginx/security.conf:/etc/nginx/security.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/senpai.online.conf:/etc/nginx/sites-enabled/senpai.online.conf:ro
      - ./../../evolve:/var/www/q6kfjhnpdimvjhkrk2fm.senpai.online/public/assets/evolve:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=q6kfjhnpdimvjhkrk2fm.senpai.online
      - NGINX_PORT=80
    command: ['nginx-debug', '-g', 'daemon off;']
    networks:
      - backend

  host:
    image: docker.io/qoomon/docker-host:2.4.0
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
